---
#
# Ansible managed
#
repository:
  description: Install and configure BareOS Console (bconsole) on your system.
  homepage: https://robertdebock.nl/
  topics: backup, bareos, infrastructure, linux, storage, system, tools, ansible, molecule, tox, playbook
