---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    # The next requiremets are included to test the connection to the Director.
    - name: robertdebock.buildtools
    - name: robertdebock.python_pip
    - name: robertdebock.postgres
    - role: robertdebock.bareos_repository
    - name: robertdebock.bareos_dir
      bareos_dir_password: "MySuperSecretPassword"
      bareos_dir_max_concurrent_jobs: 10
      bareos_dir_message: Daemon
      bareos_dir_messages:
        - name: "Standard"
          director: "dir-1 = all, !skipped, !restored"
          description: "Send all messages to the Director."
